theme: jekyll-theme-minimal

title: NAScontrol (remote)
description: A NAS control project (remote)
logo: https://github.com/eurovibes/nascontrol-remote/raw/master/images/nascontrol.png
show_downloads: true

github:
  zip_url: downloads/fabrication.zip
  tar_url: downloads/fabrication.tar.gz
