M48
; DRILL file {KiCad 7.0.9-7.0.9~ubuntu23.04.1} date Sat Jan 20 22:40:39 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-20T22:40:39+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9-7.0.9~ubuntu23.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1280
%
G90
G05
T1
X4.1608Y-2.939
X4.1608Y-3.439
T0
M30
